Ajout du raccourci CTRL X
totomatix/RaccourcisVSCode pull request #10
Opened 2023-04-05 08:54 UTC by Philippec34

2023-04-05 08:58 UTC, totomatix requested changes
LE GIF doit montrer l'effet du raccourci sur VSCode et pas sur Word.
Il faut supprimer la ligne vide avant le titre.
Enlever la majuscule à "Couper" dans le descriptif.
Ajouter les textes alternatifs pour les images des touches.
Ce raccourci permet de couper une ligne entière simplement en y plaçant le curseur, il faudrait ajouter dans le descriptif et dans le GIF cette possibilité.

2023-04-05 09:01 UTC, marklhor approved these changes

2023-04-05 09:16 UTC, SylvainTorrenti approved these changes

2023-04-05 09:26 UTC, totomatix requested changes
Il faut enlever la ligne vide avant le titre.
Il faut sauter une ligne entre le titre et le descriptif.
Le titre doit être à l'infinitif : "Couper"

2023-04-05 09:31 UTC, totomatix approved these changes
OK pour moi !

2023-04-05 09:32 UTC, j0j021 approved these changes

2023-04-05 16:23 UTC, llissandre requested changes
Mettre "Couper une zone de texte CTRL+X" dans le texte alternatif

2023-04-06 10:33 UTC, llissandre requested changes

2023-04-06 10:33 UTC, llissandre commented on raccourcis/ctrl_x.md
> +### Couper une zone de texte CTRL+ X
1. Mettre un espace avant le "+"
2. Pour le titre, je mettrais "Couper une zone de texte avec CTRL + X"

2023-04-06 10:33 UTC, llissandre commented on raccourcis/ctrl_x.md
> +**Descriptif :** Permet de couper une ligne entière ou une zone de texte sélectionnée.
Pour le descriptif, je mettrais "Permet de couper la ligne où est positionné le curseur ou une zone de texte sélectionnée, qui sera mise dans le presse-papier"

2023-04-06 10:33 UTC, llissandre commented on raccourcis/ctrl_x.md
> +**Combinaison de touches :**![ctrl](../touches/CTRL.png) + ![X](../touches/X.png)
Mettre un espace après les ":"

2023-04-06 10:33 UTC, llissandre commented on raccourcis/ctrl_x.md
> +**Visuel :** ![Coupe une zone de texte CTRL+X](../gifs/CTRL.X.gif)
Modifier le texte alternatif du visuel et mettre la même chose que dans le titre

2023-04-07 07:36 UTC, marklhor approved these changes

2023-04-07 07:36 UTC, marklhor approved these changes

2023-04-07 07:54 UTC, Jeremy-Sabadie approved these changes

2023-04-07 07:57 UTC, marklhor approved these changes

2023-04-07 07:57 UTC, j0j021 approved these changes

2023-04-07 07:58 UTC, SylvainTorrenti approved these changes

2023-04-07 08:01 UTC, saidi71 approved these changes

2023-04-07 08:24 UTC, llissandre approved these changes

2023-04-07 08:55 UTC, merged