commit, ajout CTRL+Slash
totomatix/RaccourcisVSCode pull request #11
Opened 2023-04-05 08:55 UTC by marklhor

demande validation

2023-04-05 09:11 UTC, j0j021 requested changes
enlever VEED.io du gif

2023-04-05 09:14 UTC, SylvainTorrenti requested changes
Veed.io sur le gif à enlever

2023-04-05 09:34 UTC, marklhor commented
impossible d'enlever le logo de la vidéo

2023-04-05 09:34 UTC, totomatix approved these changes
OK pour moi !

2023-04-05 09:54 UTC, saidi71 commented on raccourcis/ctrl_slash.md
> +**Descriptif :** Permet mettre en commentaire la ligne actuelle ou la sélection en cours
permet de mettre toute la ligne en .........

2023-04-05 09:54 UTC, saidi71 commented on raccourcis/ctrl_slash.md
> +### Insérer un commentaire CTRL+/ ###
Changer "Insérer" par "Mettre"

2023-04-06 07:38 UTC, SylvainTorrenti commented on raccourcis/ctrl_slash.md
> +### Insérer un commentaire CTRL+/ ###
Plutôt écrire:
"Permet d'insérer un commentaire ou de mettre la sélection en commentaire"
Suggestion

2023-04-06 07:58 UTC, llissandre requested changes

2023-04-06 07:58 UTC, llissandre commented on raccourcis/ctrl_slash.md
> +### Insérer un commentaire CTRL+/ ###
Pour le descriptif, je mettrais plutôt "Commenter la sélection en cours ou la ligne où est situé le curseur"

2023-04-06 07:58 UTC, llissandre commented on raccourcis/ctrl_slash.md
> +**Descriptif :** Permet mettre en commentaire la ligne actuelle ou la sélection en cours
Pour le titre, je mettrais plutôt "Permet de commenter la sélection en cours ou la ligne où est situé le curseur"

2023-04-06 07:58 UTC, llissandre commented on raccourcis/ctrl_slash.md
> +**Visuel :** ![Insérer un commentaire CTRL+/](./gifs/CTRL_Slash.gif)
Modifier le texte alternatif du visuel

2023-04-06 07:58 UTC, llissandre commented on raccourcis/ctrl_slash.md
> +### Insérer un commentaire CTRL+/ ###
Comme tu mets des espaces pour l'affichage des touches entre les touches, je ferais de même dans le titre

2023-04-06 10:42 UTC, llissandre requested changes

2023-04-06 10:42 UTC, llissandre commented on raccourcis/ctrl_slash.md
> +**Combinaison de touches :**![ctrl](../touches/CTRL.png) + ![/](../touches/SLASH.png)
Mettre un espace après ":"

2023-04-07 07:38 UTC, j0j021 approved these changes

2023-04-07 07:45 UTC, SylvainTorrenti approved these changes

2023-04-07 07:55 UTC, llissandre requested changes
Pour le titre, je mettrais plutôt "Commenter la ligne entière où est positionné le curseur ou une zone sélectionnée avec CTRL + /"

2023-04-07 07:59 UTC, saidi71 approved these changes

2023-04-07 08:06 UTC, llissandre approved these changes

2023-04-07 08:07 UTC, saidi71 approved these changes

2023-04-07 09:11 UTC, Philippec34 approved these changes

2023-04-07 09:18 UTC, merged