Laurent ctrl maj entree
totomatix/RaccourcisVSCode pull request #12
Opened 2023-04-05 09:50 UTC by llissandre

Création du raccourci CTRL+MAJ+ENTRÉE

2023-04-05 09:52 UTC, Philippec34 approved these changes

2023-04-05 09:53 UTC, totomatix requested changes

2023-04-05 09:53 UTC, totomatix commented on raccourcis/ctrl_maj_entree.md
> +### Sélectionner la ligne actuelle CTRL+MAJ+ENTRÉE ###
Il faut sauter une ligne entre le titre et le descriptif

2023-04-05 09:53 UTC, totomatix commented on raccourcis/ctrl_maj_entree.md
> +**Descriptif :** Permet d'ajouter une ligne avant la ligne sélectionnée
Je dirais plutôt "au dessus" que "avant"

2023-04-05 09:53 UTC, totomatix commented on raccourcis/ctrl_maj_entree.md
> +**Visuel :** ![Sélectionner la ligne actuelle CTRL+MAJ+ENTRÉE](./gifs/CTRL-MAJ-ENTREE.gif)
Tu as oublié de commité le GIF

2023-04-05 11:30 UTC, SylvainTorrenti requested changes

2023-04-05 11:30 UTC, SylvainTorrenti commented on raccourcis/ctrl_maj_entree.md
> +**Combinaison de touches :**![ctrl](../touches/CTRL.png) + ![maj](../touches/MAJ.png) + ![entree](../touches/ENTREE.png) <!-- La touche ENTRÉE sera visible après son ajout dans "touches" -->
Soucis d'affichage de la touche "entree"

2023-04-05 15:02 UTC, llissandre commented on raccourcis/ctrl_maj_entree.md
> +**Combinaison de touches :**![ctrl](../touches/CTRL.png) + ![maj](../touches/MAJ.png) + ![entree](../touches/ENTREE.png) <!-- La touche ENTRÉE sera visible après son ajout dans "touches" -->
<!-- La touche ENTRÉE sera visible après son ajout dans le répertoire "touches" -->

2023-04-06 06:48 UTC, llissandre commented on raccourcis/ctrl_maj_entree.md
> +**Combinaison de touches :**![ctrl](../touches/CTRL.png) + ![maj](../touches/MAJ.png) + ![entree](../touches/ENTREE.png) <!-- La touche ENTRÉE sera visible après son ajout dans "touches" -->
<!-- La touche ENTRÉE sera visible après son ajout dans le dossier "touches" -->

2023-04-06 07:35 UTC, SylvainTorrenti approved these changes

2023-04-06 11:44 UTC, marklhor approved these changes

2023-04-06 12:46 UTC, Philippec34 approved these changes

2023-04-07 06:39 UTC, saidi71 approved these changes

2023-04-07 07:27 UTC, Jeremy-Sabadie approved these changes

2023-04-07 07:36 UTC, totomatix approved these changes

2023-04-07 07:37 UTC, merged