Raccourci ALT+MAJ+I
totomatix/RaccourcisVSCode pull request #13
Opened 2023-04-05 12:00 UTC by SylvainTorrenti

Raccourci ALT+MAJ+I
Ajout de la touche I (image)

2023-04-05 12:05 UTC, j0j021 approved these changes

2023-04-06 06:42 UTC, j0j021 approved these changes

2023-04-06 10:55 UTC, llissandre requested changes

2023-04-06 10:55 UTC, llissandre commented on raccourcis/maj_alt_i.md
> +### Positionner plusieurs curseurs pour la sélection ALT + MAJ + I
Pour le titre, je mettrais plutôt "Positionner le curseur à la fin de chaque ligne de la zone sélectionnée avec ALT + MAJ + I"

2023-04-06 10:55 UTC, llissandre commented on raccourcis/maj_alt_i.md
> +**Descriptif :** Permet de positionner des curseurs à la fin de toutes les lignes de notre sélection et à la fin de la sélection.
Pour le descriptif, je mettrais plutôt "Permet de positionner le curseur à la fin de chaque ligne de la zone sélectionnée, et d'opérer des modifications simultanément aux différents emplacements"

2023-04-06 10:55 UTC, llissandre commented on raccourcis/maj_alt_i.md
> +**Visuel :** ![Positionner plusieurs curseurs pour la sélection ALT + MAJ + I](./gifs/ALT-MAJ-I.gif)
Modifier le texte alternatif du visuel

2023-04-06 11:32 UTC, SylvainTorrenti commented
Modification effectuées

2023-04-06 11:44 UTC, marklhor approved these changes

2023-04-06 12:27 UTC, totomatix approved these changes
OK pour moi.

2023-04-06 13:31 UTC, llissandre requested changes

2023-04-06 13:31 UTC, llissandre commented on raccourcis/maj_alt_i.md
> +**Combinaison de touches :**![alt](../touches/ALT.png) + ![maj](../touches/MAJ.png) + ![i](../touches/I.png)
Mettre un espace après **Combinaison de touches :**

2023-04-06 13:50 UTC, llissandre approved these changes
On verra ensemble si on met "avec" avant le raccourci dans le titre

2023-04-07 06:32 UTC, j0j021 approved these changes

2023-04-07 06:41 UTC, llissandre approved these changes

2023-04-07 06:49 UTC, saidi71 approved these changes

2023-04-07 07:20 UTC, j0j021 approved these changes

2023-04-07 07:21 UTC, merged