maj_alt_a
totomatix/RaccourcisVSCode pull request #14
Opened 2023-04-05 12:01 UTC by j0j021

2023-04-06 07:14 UTC, llissandre commented on raccourcis/maj_alt_a.md
> +**Visuel:**![Basculer le bloc de commentaire](gifs/maj_alt_a.gif)
Il manque l'espace avant le ":" après visuel

2023-04-06 07:24 UTC, llissandre requested changes

2023-04-06 07:24 UTC, llissandre commented on raccourcis/maj_alt_a.md
> +###Basculer le commentaire de bloc MAJ +ALT + A
Pour le titre, je pense qu'il faudrait mettre autre chose que la traduction.
Quelque chose comme "Commenter un bloc ou ajouter une zone de commentaire où est le curseur"

2023-04-06 07:25 UTC, SylvainTorrenti requested changes

2023-04-06 07:25 UTC, SylvainTorrenti commented on raccourcis/maj_alt_a.md
> +**Descriptif:** Permet de commenter le bloc de texte sélectionné.
je suis d'accord

2023-04-06 07:25 UTC, SylvainTorrenti commented on raccourcis/maj_alt_a.md
> +**Descriptif:** Permet de commenter le bloc de texte sélectionné.
je suis d'accord

2023-04-06 07:25 UTC, SylvainTorrenti commented on raccourcis/maj_alt_a.md
> +**Visuel:**![Basculer le bloc de commentaire](gifs/maj_alt_a.gif)
je suis d'accord

2023-04-06 07:25 UTC, SylvainTorrenti commented on raccourcis/maj_alt_a.md
> +###Basculer le commentaire de bloc MAJ +ALT + A
je suis d'accord

2023-04-06 07:29 UTC, SylvainTorrenti requested changes

2023-04-06 07:29 UTC, SylvainTorrenti commented on raccourcis/maj_alt_a.md
> +**Visuel:**![Basculer le bloc de commentaire](gifs/maj_alt_a.gif)
je suis d'accord

2023-04-06 07:31 UTC, SylvainTorrenti commented on raccourcis/maj_alt_a.md
> +###Basculer le commentaire de bloc MAJ +ALT + A
je suis d'accord

2023-04-06 11:43 UTC, marklhor approved these changes

2023-04-06 12:17 UTC, totomatix requested changes

2023-04-06 12:17 UTC, totomatix commented on raccourcis/maj_alt_a.md
> +### Commenter/décommenter un bloc + ALT + A
La combinaison de touches du titre n'est pas bien séparer du reste du titre

2023-04-06 12:17 UTC, totomatix commented on raccourcis/maj_alt_a.md
> +**Descriptif:** Permet de commenter/décommenter le bloc de texte sélectionné.
Il manque l'espace avant les ":"

2023-04-06 12:41 UTC, Philippec34 requested changes

2023-04-06 12:41 UTC, Philippec34 commented on raccourcis/maj_alt_a.md
> +**Visuel :**![Basculer le bloc de commentaire](gifs/maj_alt_a.gif)
Le titre et le texte alternatif ne correspondent pas.

2023-04-06 13:29 UTC, llissandre requested changes

2023-04-06 13:29 UTC, llissandre commented on raccourcis/maj_alt_a.md
> +**Combinaison de touches :** ![MAJ](../touches/MAJ.png)+![ALT](../touches/ALT.png)+![A](../touches/A.png)
Pour le descriptif, j'aurais plutôt dit : "Permet de commenter et dé-commenter un bloc de texte sélectionné, mais permet aussi d'ajouter une zone de commentaire où est le curseur"

2023-04-06 13:29 UTC, llissandre commented on raccourcis/maj_alt_a.md
> +### Commenter/décommenter un bloc + MAJ + ALT + A
Pour le titre, j'aurais plutôt dit : "Commenter ou dé-commenter un bloc de texte sélectionné, et ajouter ou retirer une zone de commentaire où est le curseur"

2023-04-06 13:29 UTC, llissandre commented on raccourcis/maj_alt_a.md
> +**Visuel :**![Basculer le bloc de commentaire](gifs/maj_alt_a.gif)
Le texte alternatif du visuel doit correspondre au titre

2023-04-06 13:46 UTC, SylvainTorrenti commented on raccourcis/maj_alt_a.md
> +**Combinaison de touches :** ![MAJ](../touches/MAJ.png)+![ALT](../touches/ALT.png)+![A](../touches/A.png)
Plutôt ?:
"Permet de commenter et dé-commenter un bloc de texte sélectionné, mais permet aussi d'ajouter une zone de commentaire où le curseur se trouve"

2023-04-07 06:52 UTC, saidi71 approved these changes

2023-04-07 07:02 UTC, saidi71 approved these changes

2023-04-07 07:29 UTC, llissandre requested changes

2023-04-07 07:29 UTC, llissandre commented on raccourcis/maj_alt_a.md
> +### Commenter/décommenter un bloc MAJ + ALT + A
Pour le titre, je mettrais "Commenter et dé-commenter un bloc de texte, et ajouter une zone de commentaire MAJ + ALT + A"

Et mettre la même chose pour le texte alternatif du visuel

2023-04-07 07:29 UTC, llissandre commented on raccourcis/maj_alt_a.md
> +**Visuel :**![Commenter/décommenter un bloc de texte](gifs/maj_alt_a.gif)
Pour le message alternatif du visuel, je mettrais comme le titre "Commenter et dé-commenter un bloc de texte, et ajouter une zone de commentaire MAJ + ALT + A"

2023-04-07 07:58 UTC, saidi71 approved these changes

2023-04-07 08:15 UTC, llissandre approved these changes

2023-04-07 08:22 UTC, SylvainTorrenti approved these changes

2023-04-07 08:51 UTC, totomatix approved these changes

2023-04-07 08:51 UTC, Philippec34 approved these changes

2023-04-07 08:52 UTC, merged