Alt + Click
totomatix/RaccourcisVSCode pull request #3
Opened 2023-04-04 14:46 UTC by SylvainTorrenti

2023-04-05 07:10 UTC, marklhor reviewed
compléter le descriptif

2023-04-05 07:59 UTC, SylvainTorrenti commented
Modification effectuer:
-Changement du descriptif

2023-04-05 09:01 UTC, llissandre requested changes
Modifier le nom du visuel
Pour le descriptif, expliquer que le raccourci permet de placer le curseur à plusieurs endroits mais au final pour effectuer des modifications à ces emplacements

2023-04-05 09:13 UTC, SylvainTorrenti commented
Modification effectuer

2023-04-05 09:14 UTC, totomatix requested changes
Il faut sauter une ligne entre le titre et le descriptif.

2023-04-05 09:15 UTC, llissandre requested changes
Descriptif : ... pour permettre les mêmes modifications aux différents emplacements.

2023-04-05 09:53 UTC, llissandre requested changes
Descriptif

2023-04-05 09:53 UTC, llissandre commented on raccourcis/alt_click.md
> +**Descriptif :** Permet de positionner plusieurs curseurs où le désire l'utilisateur pour permettre la modification.
... pour effectuer des modifications à ces emplacements

2023-04-06 10:08 UTC, llissandre requested changes

2023-04-06 10:08 UTC, llissandre commented on raccourcis/alt_click.md
> +### Positionner plusieurs curseurs ALT+Click
Pour le titre, je mettrais plutôt "Positionner le curseur à plusieurs emplacements avec ALT + Click"

2023-04-06 10:08 UTC, llissandre commented on raccourcis/alt_click.md
> +**Descriptif :** Permet de positionner plusieurs curseurs où le désire l'utilisateur pour permettre la modification.
Pour la description, je mettrais plutôt "Permet de positionner le curseur à plusieurs emplacements pour effectuer des modifications simultanées"

2023-04-06 10:08 UTC, llissandre commented on raccourcis/alt_click.md
> +**Visuel :** ![Positionner plusieurs curseurs ALT+Click](./gifs/ALT-Click.gif)
Pour le texte alternatif du visuel, je mettrais "Positionner le curseur à plusieurs emplacements avec ALT + Click" comme pour le titre

2023-04-06 11:58 UTC, SylvainTorrenti commented
Modification faites

2023-04-06 12:44 UTC, llissandre approved these changes
on verra ensemble si on met "avec" avant le raccourci dans le titre

2023-04-06 13:45 UTC, Philippec34 approved these changes

2023-04-07 06:47 UTC, saidi71 approved these changes

2023-04-07 06:55 UTC, j0j021 approved these changes

2023-04-07 07:05 UTC, j0j021 approved these changes

2023-04-07 07:10 UTC, totomatix approved these changes

2023-04-07 07:13 UTC, Jeremy-Sabadie approved these changes

2023-04-07 07:15 UTC, merged