Ctrl+ALT+Haut/Bas
totomatix/RaccourcisVSCode pull request #4
Opened 2023-04-04 14:56 UTC by SylvainTorrenti

Ctrl+ALT+Haut/Bas

2023-04-05 07:10 UTC, j0j021 approved these changes

2023-04-05 07:11 UTC, marklhor reviewed
compléter le descriptif

2023-04-05 07:12 UTC, j0j021 approved these changes

2023-04-05 07:15 UTC, saidi71 approved these changes

2023-04-05 07:46 UTC, saidi71 approved these changes

2023-04-05 07:51 UTC, SylvainTorrenti commented
Modification effectuer:
-Changement du GIF pour montrer toutes les possibilités.
-Changement du descriptif.

2023-04-05 09:07 UTC, llissandre requested changes
Pour le descriptif, expliquer que le raccourci permet de positionner le curseur sur plusieurs lignes (mais au final) pour effectuer des modifications à ces emplacements

2023-04-05 09:13 UTC, totomatix requested changes
1. Il faut sauter une ligne entre le titre et le descriptif
2. Le descriptif doit commencer par : "Permet de ..."

2023-04-06 10:01 UTC, llissandre requested changes

2023-04-06 11:54 UTC, SylvainTorrenti commented
Modification faites

2023-04-06 13:43 UTC, Philippec34 approved these changes

2023-04-07 06:38 UTC, llissandre requested changes
Je mettrais "des modifications simultanées à la fin"

2023-04-07 06:38 UTC, llissandre commented on raccourcis/ctrl_maj_alt_fleches.md
> +
Je mettrais "des modifications simultanées à la fin"

2023-04-07 06:40 UTC, llissandre requested changes

2023-04-07 06:40 UTC, llissandre commented on raccourcis/ctrl_maj_alt_fleches.md
> +
ou "d'opérer des modifications simultanément aux différents emplacements." comme sur ALT-MAJ-I

2023-04-07 07:15 UTC, saidi71 approved these changes

2023-04-07 07:23 UTC, marklhor approved these changes

2023-04-07 07:52 UTC, j0j021 approved these changes

2023-04-07 08:08 UTC, saidi71 approved these changes

2023-04-07 08:50 UTC, totomatix approved these changes

2023-04-07 08:50 UTC, merged