Jojo21 ctrl entre
totomatix/RaccourcisVSCode pull request #5
Opened 2023-04-05 08:00 UTC by j0j021

2023-04-05 08:36 UTC, SylvainTorrenti requested changes
Modification demandées:
-Ajout de la combinaison de touche dans le titre.
-Changement du descriptif.

2023-04-05 08:58 UTC, marklhor reviewed
un saut de ligne en trop en 2eme ligne

question sur le texte de remplacement

2023-04-05 09:16 UTC, totomatix requested changes
1. Il y'a un saut de ligne en trop entre le titre et le descriptif

2023-04-05 09:45 UTC, SylvainTorrenti requested changes

2023-04-05 09:45 UTC, SylvainTorrenti commented on raccourcis/ctrl_entree.md
> +### Insérer la ligne ci-dessous CTRL +ENTREE###
Enlever les # après entree

2023-04-05 09:48 UTC, totomatix requested changes

2023-04-05 09:48 UTC, totomatix commented on raccourcis/ctrl_entree.md
> +### Insérer la ligne ci-dessous CTRL +ENTREE
Mettre un espace entre "+" et "ENTREE"

2023-04-05 09:51 UTC, Philippec34 approved these changes

2023-04-05 09:57 UTC, saidi71 approved these changes

2023-04-06 08:24 UTC, SylvainTorrenti approved these changes

2023-04-06 09:17 UTC, llissandre requested changes

2023-04-06 09:17 UTC, llissandre commented on raccourcis/ctrl_entree.md
> +**Descriptif :** Permet d'insérer une ligne en dessous du curseur où qu'il soit positionné sur la ligne
Pour le titre, je mettrais plutôt "Permet d'ajouter une ligne en dessous de la ligne où est positionné le curseur avec CTRL + ENTRÉE"

2023-04-06 09:17 UTC, llissandre commented on raccourcis/ctrl_entree.md
> +**Visuel :**![Insérer une ligne ](gifs/CtrlEntre.gif)
Modifier le texte alternatif du visuel et mettre celui du titre modifié

2023-04-06 09:17 UTC, llissandre commented on raccourcis/ctrl_entree.md
> +**Combinaison de touches :** ![Ctrl](../touches/CTRL.png)+![Entrée](../touches/ENTREE.png)
Mettre des espaces avant et après le "+"

2023-04-07 07:14 UTC, saidi71 approved these changes

2023-04-07 07:50 UTC, Jeremy-Sabadie approved these changes

2023-04-07 07:52 UTC, llissandre requested changes

2023-04-07 07:52 UTC, llissandre commented on raccourcis/ctrl_entree.md
> +**Descriptif :** Permet d'insérer une ligne en dessous du curseur où qu'il soit positionné sur la ligne.
Je mettrais plutôt "Ajouter une ligne en dessous de la ligne où est positionné le curseur"

2023-04-07 08:05 UTC, saidi71 approved these changes

2023-04-07 08:05 UTC, llissandre approved these changes

2023-04-07 08:05 UTC, saidi71 approved these changes

2023-04-07 08:50 UTC, marklhor approved these changes

2023-04-07 08:50 UTC, totomatix approved these changes

2023-04-07 08:50 UTC, merged