Patrick alt z
totomatix/RaccourcisVSCode pull request #6
Opened 2023-04-05 08:05 UTC by marklhor

demande validation

2023-04-05 08:28 UTC, SylvainTorrenti requested changes
Erreur sur le GIF. 
Toujours présence de la marque du site

2023-04-05 09:19 UTC, totomatix approved these changes
OK pour moi !

2023-04-05 09:50 UTC, Philippec34 approved these changes

2023-04-05 09:54 UTC, Jeremy-Sabadie approved these changes

2023-04-05 09:58 UTC, marklhor commented
impossible d'enlever le logo sur la vidéo

2023-04-06 07:48 UTC, SylvainTorrenti approved these changes

2023-04-06 07:56 UTC, totomatix requested changes
J'avais approuvé la pull request mais en fait tu as confondu ALT-Z avec CTRL-Z. Du coup il faut changer le titre, le descriptif et le visuel.

2023-04-06 07:57 UTC, llissandre requested changes

2023-04-06 07:57 UTC, llissandre commented on raccourcis/alt_z.md
> +### Retour arrière ALT+Z
Comme tu mets des espaces pour l'affichage des touches entre les touches, je ferais de même dans le titre

2023-04-06 10:15 UTC, llissandre requested changes

2023-04-06 10:15 UTC, llissandre commented on raccourcis/alt_z.md
> +**Descriptif :** Permer d'annuler les oppérations précédentes, de revenir en arrière sur les actions réalisées.
Le raccourci permet d'adapter les lignes à la zone d'affichage

2023-04-06 10:15 UTC, llissandre commented on raccourcis/alt_z.md
> +**Visuel :** ![Retour arrière ALT+Z](./gifs/ALT_Z.gif)
Modifier le GIF pour montrer ce que fait ALT+Z

2023-04-06 11:50 UTC, marklhor commented on raccourcis/alt_z.md
> +**Visuel :** ![Retour arrière ALT+Z](./gifs/ALT_Z.gif)
je comprends pas ta remarque, vu que la vidéo le montre

2023-04-06 11:50 UTC, marklhor commented on raccourcis/alt_z.md
> +**Descriptif :** Permer d'annuler les oppérations précédentes, de revenir en arrière sur les actions réalisées.
de quelle zone d'affichage parles tu ?

2023-04-06 13:07 UTC, SylvainTorrenti requested changes
Raccourci pas bon c'est alt + Z et non ctrl + Z

2023-04-06 13:07 UTC, SylvainTorrenti commented on raccourcis/alt_z.md
> +**Descriptif :** Permer d'annuler les oppérations précédentes, de revenir en arrière sur les actions réalisées.
Remplacer "permer" par "Permet"

2023-04-06 13:41 UTC, Philippec34 approved these changes

2023-04-07 06:35 UTC, j0j021 approved these changes

2023-04-07 07:13 UTC, saidi71 approved these changes

2023-04-07 07:44 UTC, SylvainTorrenti approved these changes

2023-04-07 07:52 UTC, Jeremy-Sabadie approved these changes

2023-04-07 07:56 UTC, j0j021 approved these changes

2023-04-07 08:03 UTC, saidi71 approved these changes

2023-04-07 08:37 UTC, llissandre requested changes

2023-04-07 08:37 UTC, llissandre commented on raccourcis/alt_z.md
> +### Basculer le retour à la ligne ALT+Z
Pour le titre, je mettrais "Adapter le texte à la zone d'affichage avec un retour à la ligne"

2023-04-07 08:37 UTC, llissandre commented on raccourcis/alt_z.md
> +**Visuel :** ![Basculer le retour à la ligne ALT+Z](./gifs/ALT_Z.gif)
Mettre le titre dans le texte alternatif

2023-04-07 08:37 UTC, llissandre commented on raccourcis/alt_z.md
> +**Descriptif :** Permet d'afficher les lignes qui débordent à droite de l'écran, de les afficher à l'écran, ou inversement.
Pour le descriptif, je mettrais "Permet d''adapter le texte à la zone d'affichage avec un retour à la ligne et ainsi d'afficher les lignes qui débordent à droite de la zone d'affichage.

2023-04-07 08:53 UTC, totomatix approved these changes

2023-04-07 08:58 UTC, llissandre approved these changes

2023-04-07 08:59 UTC, merged