Jeremy alt+haut
totomatix/RaccourcisVSCode pull request #7
Opened 2023-04-05 08:09 UTC by Jeremy-Sabadie

2023-04-05 08:16 UTC, j0j021 approved these changes

2023-04-05 08:26 UTC, SylvainTorrenti requested changes
Modification du descriptif

2023-04-05 08:57 UTC, marklhor reviewed
manque saute de ligne entre 1er et 2eme ligne

2023-04-05 09:20 UTC, totomatix requested changes
1. Il faut sauter en ligne entre le titre et le descriptif
2. Il faut des espaces avant et après le caractère ":"

2023-04-05 09:41 UTC, totomatix approved these changes
OK pour moi !

2023-04-05 09:41 UTC, SylvainTorrenti approved these changes

2023-04-05 09:49 UTC, Philippec34 approved these changes

2023-04-05 09:53 UTC, SylvainTorrenti requested changes

2023-04-05 09:53 UTC, SylvainTorrenti commented on raccourcis/alt_fleches.md
> +### Déplacer une ligne au dessus/au dessous ###
Ajout de la combinaison de touche

2023-04-06 09:34 UTC, llissandre requested changes

2023-04-06 09:34 UTC, llissandre commented on raccourcis/alt_fleches.md
> +### Déplacer une ligne au dessus/au dessous ###
Pour le titre, je mettrais "Déplacer la ligne où est le curseur au-dessus ou en dessous avec ALT + HAUT/BAS"

2023-04-06 09:34 UTC, llissandre commented on raccourcis/alt_fleches.md
> +**Combinaison de touches :**![ALT](../touches/ALT.png) + ![flèvhe haut](../touches/HAUT.png)/![flèvhe bas](../touches/BAS.png)
Mettre un espace après les ":"

2023-04-07 07:57 UTC, marklhor approved these changes

2023-04-07 08:00 UTC, SylvainTorrenti approved these changes

2023-04-07 08:03 UTC, saidi71 approved these changes

2023-04-07 08:30 UTC, llissandre requested changes

2023-04-07 08:30 UTC, llissandre commented on raccourcis/alt_fleches.md
> +### Déplacer la ligne sur laquelle se trouve le curseur au dessus/au dessous alt + haut/bas
Orthographe
Pour le titre, je mettrais plutôt : "Déplacer la ligne sur laquelle se trouve le curseur au-dessus ou en dessous ALT + HAUT/BAS"

2023-04-07 08:33 UTC, j0j021 approved these changes

2023-04-07 08:59 UTC, llissandre approved these changes

2023-04-07 09:01 UTC, j0j021 approved these changes

2023-04-07 09:17 UTC, merged