Raccourci CTRL+MAJ+L
totomatix/RaccourcisVSCode pull request #8
Opened 2023-04-05 08:24 UTC by SylvainTorrenti

2023-04-05 08:56 UTC, marklhor reviewed
manque saut de ligne, entre la première ligne et la deuxième ligne

2023-04-05 09:22 UTC, totomatix requested changes
1. Il faut sauter une ligne entre le titre et le descriptif
2. Il manque le GIF, le GIF actuel est celui de CTRL-L
3. Le descriptif ne correspond pas au raccourci

2023-04-05 09:35 UTC, totomatix approved these changes
OK pour moi !

2023-04-05 09:37 UTC, j0j021 requested changes
dans le titre il manque un accent à sélection

2023-04-05 09:47 UTC, Philippec34 approved these changes

2023-04-06 07:43 UTC, SylvainTorrenti commented
Je ne vois pas où l'accent manque

2023-04-06 08:16 UTC, llissandre requested changes

2023-04-06 08:16 UTC, llissandre commented on raccourcis/ctrl_maj_l.md
> +### Sélectionner toutes les occurences du mot ou de la selection CTRL+MAJ+L
1. Pour le titre, je mettrais plutôt "Sélectionner toutes les occurrences du mot où est positionné le curseur ou d'une sélection (orthographe : occurrences et sélection).
2. Comme tu mets des espaces pour l'affichage des touches entre les touches, je ferais de même dans le titre, avant et après les "+"

2023-04-06 08:16 UTC, llissandre commented on raccourcis/ctrl_maj_l.md
> +**Descriptif :** Permet de sélectionner toutes les occurences du mot, où le curseur est positionné, ou de la selection en cour.
1. Pour le descriptif, je mettrais plutôt "Permet de sélectionner toutes les occurrences du mot où est positionné le curseur ou d'une sélection, ce qui permet d'effectuer des modifications sur tous les éléments en même temps.
2. Mettre un espace après les ":"

2023-04-06 08:16 UTC, llissandre commented on raccourcis/ctrl_maj_l.md
> +**Combinaison de touches :**![ctrl](../touches/CTRL.png) +![maj](../touches/MAJ.png)+ ![l](../touches/L.png)
1. Si tu mets un espace avant le "+", en mettre un après
2. Mettre un espace après les ":"

2023-04-06 08:16 UTC, llissandre commented on raccourcis/ctrl_maj_l.md
> +**Visuel :** ![Sélectionner toutes les occurences du mot ou de la selection CTRL+MAJ](./gifs/Ctrl-Maj-L.gif)
1. Modifier le texte alternatif du visuel
2. Mettre un espace après les ":"

2023-04-06 11:38 UTC, SylvainTorrenti commented
changement fait

2023-04-06 13:16 UTC, Philippec34 approved these changes

2023-04-07 07:03 UTC, saidi71 approved these changes

2023-04-07 07:21 UTC, Jeremy-Sabadie approved these changes

2023-04-07 07:23 UTC, marklhor approved these changes

2023-04-07 07:49 UTC, j0j021 approved these changes

2023-04-07 07:49 UTC, merged