Saidi ctrl c
totomatix/RaccourcisVSCode pull request #9
Opened 2023-04-05 08:42 UTC by saidi71

2023-04-05 08:46 UTC, totomatix requested changes
Le nom du raccourci n'est pas correct.
Il faut mettre les images des touches dans la combinaison de touches.
Ce raccourci permet de copier la ligne sans avoir à la sélectionner, il suffit juste de placer le curseur sur la ligne, il faut donc changer : 

1. le gif pour refléter cette possibilité
2. La description pour expliquer cette possibilité

2023-04-05 09:00 UTC, marklhor reviewed
ne correspond pas, il me semble, au format type demandé CTRL+L

2023-04-05 09:28 UTC, j0j021 requested changes
il y a des fautes dans la description :  sans avoir à la sélectionner

2023-04-05 09:28 UTC, totomatix requested changes
1. Changer "Description" par "Descriptif"
2. Il y'a un "le" en trop dans le descriptif
3. Le gif n'est pas placé au bon endroit dans l'arborescence de fichiers

2023-04-05 09:46 UTC, totomatix approved these changes
OK pour moi !

2023-04-05 16:21 UTC, llissandre requested changes
![image](https://user-images.githubusercontent.com/118750600/230142652-f1611eaa-d49a-4a9d-a056-36cd649fc542.png)

Il y a un soucis avec les fichiers

2023-04-06 07:39 UTC, SylvainTorrenti approved these changes

2023-04-06 10:25 UTC, llissandre requested changes

2023-04-06 10:25 UTC, llissandre commented on raccourcis/ctrl_c.md
> +**Combinaison de touches :** ![ctrl](../touches/CTRL.png) + ![C](../touches/C.png)
Mettre la combinaison de touches après le descriptif

2023-04-06 10:25 UTC, llissandre commented on raccourcis/ctrl_c.md
> +### Copier la line ou l'élément sélectionné CTRL+C  ###
Pour le titre, je mettrais plutôt "Copier une ligne ou un élément sélectionné avec CTRL + C"

2023-04-06 10:25 UTC, llissandre commented on raccourcis/ctrl_c.md
> +**Description :** Permet de copier le contenu sélectionné ou de copier la ligne complète sans avoir à la sélectionner, il suffit simplement de mettre le curseur sur la ligne.
1. -Mettre Descriptif au lieu de Description
2. Pour le descriptif, je mettrais plutôt "Permet de copier la ligne où est le curseur ou une sélection, qui sera mise dans le presse-papier"

2023-04-06 10:25 UTC, llissandre commented on raccourcis/ctrl_c.md
> +**Visuel :** ![ CTRL+C](./gifs/CTRL+C.gif)
Modifier le texte alternatif du visuel et mettre ce qu'il y a dans le titre

2023-04-06 13:12 UTC, Philippec34 approved these changes

2023-04-07 07:48 UTC, j0j021 approved these changes

2023-04-07 07:50 UTC, llissandre approved these changes

2023-04-07 07:50 UTC, llissandre commented on raccourcis/ctrl_c.md
> +### Copier la ligne ou le contenu sélectionné CTRL+C
Mettre un espace avant et après le "+"

2023-04-07 07:50 UTC, llissandre commented on raccourcis/ctrl_l.md
> +**Visuel :** ![Sélectionner la ligne actuelle CTRL+L](./gifs/CTRL-L.gif)
Mettre un espace avant et après le "+"

2023-04-07 07:53 UTC, marklhor approved these changes

2023-04-07 07:54 UTC, merged